Integrate daily log data into homepage card  Issue #58
cse110-sp24-group6/cse110-sp24-group6 pull request #60
Opened 2024-06-02 02:39 UTC by ronadarabi

## Pull request summary:
Connected daily log data to homepage so that there is a streak counter that shows how many consecutive days user has created logs. The circles on the homepage also become checked for every day of the week that there is a log. 

## Type of change (bug, feature, design, logistics, etc):
Feature

## How has this been tested (if applicable):
Tested by adding and deleting logs

## Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have tested that my changes work (locally and via unit testing)
- [x] I have assigned atleast 2 reviewers to look at and review my code quality
- [x] Documentation has been updated
- [x] Code follows style guidelines

2024-06-02 07:41 UTC, hc225 commented
If one was to fill in multiple logs of the week in a day, should it still count as streak?
There is the part where daily logs can be filled beforehand for the week, which adds to the streak (e.g. Today is Sunday, but I fill Mon–Sat)
There is also part where missed previous logs can add to the streak, but only if today's log is done (e.g. Today is Sat, but I fill Sun–Sat and get a 7 day streak, though filling only Sun–Fri will be 0 streak)

2024-06-03 00:48 UTC, ronadarabi commented
Good points! I worked on the 2nd point and pushed it (accidentally to the Daily Log CSS branch, not this one).

2024-06-03 02:20 UTC, NathanTzChung requested changes
Looks great overall! Just want to make sure that the comment regarding the ID for the days of the week in the HTML gets checked.

2024-06-03 02:20 UTC, NathanTzChung commented on source/homepage.html
For changing the id's to integers, I think there is a conflict with the CSS. Is there a quick fix for making kebab-case for integers? In the CSS, in order to make the circles, I refer to the id's as #sunday-circle etc. When using #0, it wouldn't pass the check for kebab-case. Is there another option for the id's?

2024-06-03 02:20 UTC, NathanTzChung commented on source/assets/scripts/dailylog.js
Just wondering, what happened here such that the code needed to be removed? (was it just not necessary?//what code replaced this if there is any?)

2024-06-03 02:23 UTC, ronadarabi commented on source/assets/scripts/dailylog.js
Yeah we decided to not do the dropdown feature because it seemed hard and not very time efficient, so I removed the code for that to keep the files clean

2024-06-03 02:24 UTC, ronadarabi commented on source/homepage.html
Ohh it just seemed easiest because the convention for .getDay() for Date objects is 0=Sunday, 1=Monday, etc, but I can just make a function to convert these numbers to the appropriate IDs

2024-06-03 02:28 UTC, NathanTzChung commented on source/homepage.html
Yeah, could you do that? Whichever ID you name then, just lmk, thanks!

2024-06-03 02:52 UTC, NathanTzChung approved these changes
I think this looks good! The main functionality is there (I did not check to see if what Henry mentioned above is accounted for though)

2024-06-03 20:43 UTC, yashilvora19 approved these changes
Nicely done. I see you've made the streak only until the current day and that's really important so no other issues that I see. Looks great to me!

2024-06-03 20:43 UTC, merged

2024-06-04 04:11 UTC, hc225 reviewed
looks good!