E2E Tests for Daily Log page- CRUD and LocalStorage
cse110-sp24-group6/cse110-sp24-group6 pull request #88
Opened 2024-06-08 05:18 UTC by yashilvora19

## Pull request summary:

- Completed end to end tests for the daily log page
- For the TODO page Emily and my tests overlap a lot so I will just be adding a few more tests in her file to test localStorage

## Type of change (bug, feature, design, logistics, etc):
Testing

## How has this been tested (if applicable):

## Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have tested that my changes work (locally and via unit testing)
- [ ] I have assigned atleast 2 reviewers to look at and review my code quality
- [ ] Documentation has been updated
- [ ] Code follows style guidelines

2024-06-08 13:52 UTC, NathanTzChung requested changes
Looks about right, but I do have question. Are the two files (with the tests) supposed to both have the same code? It looks like dailyLogCRUD.test.js is the same as todoListCRUD.js? I might just be misunderstanding something though.

2024-06-08 19:00 UTC, yashilvora19 commented
> Looks about right, but I do have question. Are the two files (with the tests) supposed to both have the same code? It looks like dailyLogCRUD.test.js is the same as todoListCRUD.js? I might just be misunderstanding something though.

Oh that's my bad, I had created a duplicate file. Let me remove it. Thanks for pointing it out.

2024-06-08 20:02 UTC, ronadarabi approved these changes
Awesome job, looks great! Codacy errors can be easily fixed or bypassed as they are minor.

2024-06-09 00:16 UTC, NathanTzChung approved these changes

2024-06-09 01:17 UTC, merged